# Site settings
author: Annette
title: Driven by Curiosity
header-img: img/home-bg.png
email: micha232@umn.edu
copyright_name: Annette
description: > # this means to ignore newlines until "baseurl:"
  Discovering my Niche
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  Rygel-XVI

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]

theme: jekyll-theme-merlot